### ISSUE TITLE
Proposal do getting into web2py

### ISSUE THREAD

**Issue by Marlysson** [willimoa/welcome_d3#2]
Which tasks need to done to send a pull request to web2py ?

**Comment by willimoa** [comment]
Hi and thanks.  Mainly taking the code and applying it to the welcome app in the Web2py GitHub repo.  Also, some tweaks to the layout but that can be refined over time.
I'll have a go at this over the weekend. Sorry, been focusssed elsewhere stopping me finishing this off.

**Comment by Marlysson** [comment]
Ok , talk with me which features you want to do to finish this , I want to help.

Ok :smile: ?

**Comment by willimoa** [comment]
Yes Please.  Nearly finished.  I'll do a Pull Request today.   Then once it is in web2py could use some help in further  optimising the layout and improving exception handling.

**Comment by Marlysson** [comment]
Great .. I'll see it n web2py .. :+1:

**Comment by willimoa** [comment]
Just completed Pull Request.    CI test is failing  - have to figure out what happened ?   
Wondering about the welcome.w2p file in web2py.  Would I have to include that in the Pull Request, or does it get created itself ?  See NEWINSTALL in online book.

**Comment by Marlysson** [comment]
I think that you have alter the welcome APP in applications, not? ..

Newinstall? Where?

**Comment by willimoa** [comment]
This code has been added to web2py/web2py.  Future updates will be applied to that repository.

**Comment by Marlysson** [comment]
Do you merged?

**Comment by willimoa** [comment]
Yes, PR #1622.

**Comment by willimoa** [comment]
Hello, yes.  Just doing a further change to remove the graphviz code.

**Comment by dz0** [comment]
Just in case (not sure if this is right place to inform), I made plugin using graphviz (with some extra features) -- so it can be used independantly of main graph_model 
https://groups.google.com/forum/#!topic/web2py/6ug3Rv7LTh8
